# IdleToken Cluster top-level Makefile.
#
# Builds two binaries:
#   idletoken-worker  — inference shard. Links full GPU ds4 (CUDA).
#   idletoken-coord   — scheduler + API server. CPU-only ds4 (-DDS4_NO_GPU).
#
# Linux + NVIDIA CUDA only -- a hard constraint. Mac is for editing;
# rsync to a Linux GPU host (DGX Spark or a home GPU machine) to build.

UNAME_S := $(shell uname -s)
ifneq ($(UNAME_S),Linux)
$(info IdleToken Cluster builds on Linux + NVIDIA CUDA only.)
$(info Detected host: $(UNAME_S). Use ./scripts/sync-to-spark.sh and build remotely.)
$(error unsupported build host)
endif

CC              ?= cc
CUDA_HOME       ?= /usr/local/cuda
NVCC            ?= $(CUDA_HOME)/bin/nvcc
NATIVE_CPU_FLAG ?= -march=native

DS4 := vendor/ds4

CFLAGS_BASE := -O3 -ffast-math $(NATIVE_CPU_FLAG) -Wall -Wextra -std=c99 \
               -D_GNU_SOURCE -fno-finite-math-only \
               -I$(DS4) -Iinclude

# Worker needs NVML headers (in CUDA toolkit, not in default sysroot).
# IDLETOKEN_DS4X_CUDA turns on the ds4x GPU matvec (the worker already links
# cudart); without it a ds4x cluster would silently serve on CPU only.
CFLAGS_WORKER := $(CFLAGS_BASE) -I$(CUDA_HOME)/include -DIDLETOKEN_DS4X_CUDA
CFLAGS_COORD  := $(CFLAGS_BASE) -DDS4_NO_GPU

NVCCFLAGS := -O3 --use_fast_math \
             -Xcompiler $(NATIVE_CPU_FLAG) -Xcompiler -pthread

# libnvidia-ml.so.1 ships with the NVIDIA driver and is usually in the linker
# default path; CUDA_HOME/lib64 is a fallback for non-standard installs.
CUDA_LDLIBS := -lm -Xcompiler -pthread \
               -L$(CUDA_HOME)/targets/sbsa-linux/lib \
               -L$(CUDA_HOME)/lib64 -lcudart -lcublas -lnvidia-ml

WORKER_BUILD := build/worker
COORD_BUILD  := build/coord

# vendor objects
DS4_WORKER_OBJ := $(WORKER_BUILD)/vendor/ds4.o \
                  $(WORKER_BUILD)/vendor/ds4_cuda.o \
                  $(WORKER_BUILD)/vendor/rax.o
DS4_COORD_OBJ  := $(COORD_BUILD)/vendor/ds4.o \
                  $(COORD_BUILD)/vendor/rax.o

# common (resource.c is worker-only — pulls in NVML; http.c is coord-only)
COMMON_SRC_SHARED   := src/common/net.c src/common/discovery.c src/common/model.c
# advise.c (capability table) needs plan.c, which used to be coord-only — the
# worker now links both so `--advise` can answer "what can THIS machine run?"
# with the planner's own verdict instead of a second estimate.
COMMON_SRC_WORKER   := $(COMMON_SRC_SHARED) src/common/resource.c src/common/weights.c src/common/gguf.c \
                       src/common/plan.c src/common/advise.c
COMMON_SRC_COORD    := $(COMMON_SRC_SHARED) src/common/http.c src/common/plan.c src/common/gguf.c \
                       src/common/advise.c
WORKER_COMMON_OBJ   := $(patsubst src/common/%.c,$(WORKER_BUILD)/common/%.o,$(COMMON_SRC_WORKER))

# ds4x generic CPU backend (small models: Qwen3 GQA, GLM/Kimi MLA). Pure C, no
# CUDA — links into the worker so a ds4x cluster serves on CPU (a CUDA kernel is
# a later speed-up, not a correctness gate). small-model-design.md §S-C.
DS4X_UNITS          := ds4x_config ds4x_model ds4x_forward ds4x_runner ds4x_quant
DS4X_WORKER_OBJ     := $(patsubst %,$(WORKER_BUILD)/ds4x/%.o,$(DS4X_UNITS)) \
                       $(WORKER_BUILD)/ds4x/ds4x_cuda.o
# Coord only needs the GGUF byte-BPE tokenizer (prompt encode + detokenize for
# ds4x models); embed/lm_head run on the workers.
DS4X_COORD_OBJ      := $(COORD_BUILD)/ds4x/ds4x_tokenizer.o
COORD_COMMON_OBJ    := $(patsubst src/common/%.c,$(COORD_BUILD)/common/%.o,$(COMMON_SRC_COORD))

# binary-specific
WORKER_MAIN_OBJ := $(WORKER_BUILD)/worker_main.o
COORD_MAIN_OBJ  := $(COORD_BUILD)/coord_main.o

.PHONY: all worker coord clean check info plantest disctest

all: worker coord

# Unit tests for the planning core (mode decision + layer split). Pure C —
# also runs on the mac control machine with plain cc.
plantest:
	$(CC) -Wall -Wextra -std=c99 -Iinclude src/common/plan.c src/common/model.c src/common/advise.c src/tools/plan_test.c -o build/plan_test
	./build/plan_test

# Unit tests for the ds4x runtime config (GGUF-metadata-driven, Phase B).
# Pure C — fixtures are metadata-only GGUFs generated by a small script.
ds4xtest:
	@mkdir -p build
	python3 scripts/make_test_gguf.py build/fixtures
	$(CC) -Wall -Wextra -std=c99 -Iinclude src/common/gguf.c src/common/model.c \
	    src/ds4x/ds4x_config.c src/tools/ds4x_config_test.c -o build/ds4x_config_test
	./build/ds4x_config_test build/fixtures
	$(CC) -Wall -Wextra -std=c99 -Iinclude src/ds4x/ds4x_quant.c \
	    src/tools/ds4x_quant_test.c -o build/ds4x_quant_test -lm
	./build/ds4x_quant_test
	python3 scripts/ds4x_ref.py build/fixtures/ds4x_vectors.bin
	$(CC) -Wall -Wextra -std=c99 -Iinclude src/common/model.c \
	    src/ds4x/ds4x_config.c src/ds4x/ds4x_forward.c src/ds4x/ds4x_model.c \
	    src/ds4x/ds4x_runner.c src/ds4x/ds4x_quant.c src/common/gguf.c \
	    src/tools/ds4x_forward_test.c -o build/ds4x_forward_test -lm
	./build/ds4x_forward_test build/fixtures/ds4x_vectors.bin build/fixtures/ds4x_vectors.bin.gguf
	python3 scripts/ds4x_ref.py build/fixtures/ds4x_noqlora.bin --q-rank 0
	./build/ds4x_forward_test build/fixtures/ds4x_noqlora.bin build/fixtures/ds4x_noqlora.bin.gguf
	python3 scripts/ds4x_ref.py build/fixtures/ds4x_q8.bin --quant q8_0
	./build/ds4x_forward_test build/fixtures/ds4x_q8.bin build/fixtures/ds4x_q8.bin.gguf
	python3 scripts/ds4x_ref.py build/fixtures/ds4x_qwen3.bin --arch qwen3
	$(CC) -Wall -Wextra -std=c99 -Iinclude src/common/model.c \
	    src/ds4x/ds4x_config.c src/ds4x/ds4x_forward.c src/ds4x/ds4x_model.c \
	    src/ds4x/ds4x_runner.c src/ds4x/ds4x_quant.c src/common/gguf.c \
	    src/tools/ds4x_gqa_test.c -o build/ds4x_gqa_test -lm
	./build/ds4x_gqa_test build/fixtures/ds4x_qwen3.bin build/fixtures/ds4x_qwen3.bin.gguf
	python3 scripts/ds4x_ref.py build/fixtures/ds4x_gdn.bin --arch qwen3next
	$(CC) -Wall -Wextra -std=c99 -Iinclude src/common/model.c \
	    src/ds4x/ds4x_config.c src/ds4x/ds4x_forward.c src/ds4x/ds4x_model.c \
	    src/ds4x/ds4x_runner.c src/ds4x/ds4x_quant.c src/common/gguf.c \
	    src/tools/ds4x_gdn_test.c -o build/ds4x_gdn_test -lm
	./build/ds4x_gdn_test build/fixtures/ds4x_gdn.bin
	$(CC) -Wall -Wextra -std=c99 -Iinclude src/common/gguf.c \
	    src/ds4x/ds4x_tokenizer.c src/tools/ds4x_tok_test.c -o build/ds4x_tok_test
	./build/ds4x_tok_test build/fixtures
	$(CC) -Wall -Wextra -std=c99 -Iinclude src/common/model.c \
	    src/ds4x/ds4x_config.c src/ds4x/ds4x_forward.c src/ds4x/ds4x_model.c \
	    src/ds4x/ds4x_runner.c src/ds4x/ds4x_tokenizer.c src/ds4x/ds4x_quant.c \
	    src/common/gguf.c \
	    src/ds4x/ds4x_infer.c -o build/ds4x_infer -lm
	./build/ds4x_infer build/fixtures/ds4x_vectors.bin.gguf --selftest build/fixtures/ds4x_vectors.bin

# CUDA parity gate: GPU dequant+matvec must match the CPU reference for every
# quant type (small-model-design §S-C). Needs nvcc + a device; on a machine
# without CUDA the binary reports SKIP (loudly) instead of a false green.
.PHONY: cudatest
cudatest:
	@mkdir -p build
	$(NVCC) $(NVCCFLAGS) -Iinclude -c -o build/ds4x_cuda.o src/ds4x/ds4x_cuda.cu
	$(CC) -Wall -Wextra -std=c99 -Iinclude -c -o build/ds4x_quant_for_cuda.o src/ds4x/ds4x_quant.c
	@# ds4x_forward.c WITHOUT -DIDLETOKEN_DS4X_CUDA: the test's reference must be
	@# the CPU path itself (ds4x_gdn_recur_cpu), never a copy of it in the test.
	$(CC) -Wall -Wextra -std=c99 -Iinclude -c -o build/ds4x_forward_for_cuda.o src/ds4x/ds4x_forward.c
	$(CC) -Wall -Wextra -std=c99 -Iinclude -c -o build/ds4x_cuda_test.o src/tools/ds4x_cuda_test.c
	$(NVCC) $(NVCCFLAGS) -o build/ds4x_cuda_test \
	    build/ds4x_cuda_test.o build/ds4x_quant_for_cuda.o \
	    build/ds4x_forward_for_cuda.o build/ds4x_cuda.o $(CUDA_LDLIBS)
	./build/ds4x_cuda_test

# CUDA-accelerated standalone inference tool (same binary as ds4x_infer, but
# with the GPU matvec compiled in). Run with IDLETOKEN_DS4X_CUDA=1 to use the GPU;
# without the env var it behaves exactly like the CPU build.
XI_CFLAGS := -O3 -march=native -Wall -Wextra -std=c99 -Iinclude -DIDLETOKEN_DS4X_CUDA
XI_CSRC   := src/common/model.c src/ds4x/ds4x_config.c src/ds4x/ds4x_forward.c \
             src/ds4x/ds4x_model.c src/ds4x/ds4x_runner.c src/ds4x/ds4x_tokenizer.c \
             src/ds4x/ds4x_quant.c src/common/gguf.c src/ds4x/ds4x_infer.c
XI_OBJ    := $(patsubst %.c,build/xi/%.o,$(notdir $(XI_CSRC)))

.PHONY: ds4xinfer-cuda
ds4xinfer-cuda:
	@mkdir -p build/xi
	$(NVCC) $(NVCCFLAGS) -Iinclude -c -o build/xi/ds4x_cuda.o src/ds4x/ds4x_cuda.cu
	@for f in $(XI_CSRC); do \
	    echo "  CC $$f"; \
	    $(CC) $(XI_CFLAGS) -c -o build/xi/`basename $$f .c`.o $$f || exit 1; \
	done
	$(NVCC) $(NVCCFLAGS) -o build/ds4x_infer_cuda $(XI_OBJ) build/xi/ds4x_cuda.o $(CUDA_LDLIBS)

# Unit tests for LAN discovery + verification-code pairing. Pure C (+pthread) —
# runs on the mac control machine and Linux nodes; no GPU/model needed.
disctest:
	@mkdir -p build
	$(CC) -Wall -Wextra -std=c99 -D_GNU_SOURCE -Iinclude \
	    src/common/net.c src/common/discovery.c src/tools/discovery_test.c \
	    -o build/discovery_test -lpthread
	./build/discovery_test

worker: idletoken-worker
coord:  idletoken-coord

idletoken-worker: $(WORKER_MAIN_OBJ) $(WORKER_COMMON_OBJ) $(DS4X_WORKER_OBJ) $(DS4_WORKER_OBJ)
	$(NVCC) $(NVCCFLAGS) -o $@ $^ $(CUDA_LDLIBS)

idletoken-coord: $(COORD_MAIN_OBJ) $(COORD_COMMON_OBJ) $(DS4X_COORD_OBJ) $(DS4_COORD_OBJ)
	$(CC) $(CFLAGS_COORD) -o $@ $^ -lm -pthread

# --- vendor/ds4 sources (worker variant, GPU on) ----------------------------

$(WORKER_BUILD)/vendor/ds4.o: $(DS4)/ds4.c $(DS4)/ds4.h $(DS4)/ds4_gpu.h | $(WORKER_BUILD)/vendor
	$(CC) $(CFLAGS_WORKER) -c -o $@ $<

$(WORKER_BUILD)/vendor/ds4_cuda.o: $(DS4)/ds4_cuda.cu $(DS4)/ds4_gpu.h $(DS4)/ds4_iq2_tables_cuda.inc | $(WORKER_BUILD)/vendor
	$(NVCC) $(NVCCFLAGS) -c -o $@ $<

$(WORKER_BUILD)/vendor/rax.o: $(DS4)/rax.c $(DS4)/rax.h $(DS4)/rax_malloc.h | $(WORKER_BUILD)/vendor
	$(CC) $(CFLAGS_WORKER) -c -o $@ $<

# --- vendor/ds4 sources (coord variant, CPU only) ---------------------------

$(COORD_BUILD)/vendor/ds4.o: $(DS4)/ds4.c $(DS4)/ds4.h $(DS4)/ds4_gpu.h | $(COORD_BUILD)/vendor
	$(CC) $(CFLAGS_COORD) -c -o $@ $<

$(COORD_BUILD)/vendor/rax.o: $(DS4)/rax.c $(DS4)/rax.h $(DS4)/rax_malloc.h | $(COORD_BUILD)/vendor
	$(CC) $(CFLAGS_COORD) -c -o $@ $<

# --- our sources -----------------------------------------------------------

$(WORKER_BUILD)/common/%.o: src/common/%.c include/idletoken_proto.h include/idletoken_net.h include/idletoken_discovery.h include/idletoken_resource.h include/idletoken_weights.h | $(WORKER_BUILD)/common
	$(CC) $(CFLAGS_WORKER) -c -o $@ $<

$(COORD_BUILD)/common/%.o: src/common/%.c include/idletoken_proto.h include/idletoken_net.h include/idletoken_discovery.h include/idletoken_http.h | $(COORD_BUILD)/common
	$(CC) $(CFLAGS_COORD) -c -o $@ $<

$(COORD_BUILD)/ds4x/%.o: src/ds4x/%.c include/idletoken_ds4x_tok.h include/idletoken_gguf.h | $(COORD_BUILD)/ds4x
	$(CC) $(CFLAGS_COORD) -c -o $@ $<

$(WORKER_BUILD)/ds4x/%.o: src/ds4x/%.c include/idletoken_ds4x.h include/idletoken_ds4x_quant.h include/idletoken_gguf.h include/idletoken_model.h | $(WORKER_BUILD)/ds4x
	$(CC) $(CFLAGS_WORKER) -c -o $@ $<

$(WORKER_BUILD)/ds4x/ds4x_cuda.o: src/ds4x/ds4x_cuda.cu include/idletoken_ds4x_cuda.h | $(WORKER_BUILD)/ds4x
	$(NVCC) $(NVCCFLAGS) -Iinclude -c -o $@ $<

$(WORKER_BUILD)/%.o: src/worker/%.c include/idletoken_proto.h include/idletoken_net.h | $(WORKER_BUILD)
	$(CC) $(CFLAGS_WORKER) -c -o $@ $<

$(COORD_BUILD)/%.o: src/coord/%.c include/idletoken_proto.h include/idletoken_net.h | $(COORD_BUILD)
	$(CC) $(CFLAGS_COORD) -c -o $@ $<

# --- dirs ------------------------------------------------------------------

$(WORKER_BUILD) $(WORKER_BUILD)/vendor $(WORKER_BUILD)/common $(WORKER_BUILD)/ds4x $(COORD_BUILD) $(COORD_BUILD)/vendor $(COORD_BUILD)/common $(COORD_BUILD)/ds4x:
	@mkdir -p $@

# --- helpers ---------------------------------------------------------------

info:
	@echo "DS4 vendor path:  $(DS4)"
	@echo "CUDA_HOME:        $(CUDA_HOME)"
	@echo "NVCC:             $(NVCC)"
	@echo "CFLAGS_WORKER:    $(CFLAGS_WORKER)"
	@echo "CFLAGS_COORD:     $(CFLAGS_COORD)"

clean:
	rm -rf build idletoken-worker idletoken-coord
